@startuml
!include .\\Program.puml
!include .\\Startup.puml
!include .\\Context\AppDbContext.puml
!include .\\Controllers\AnswerController.puml
!include .\\Controllers\GenericController.puml
!include .\\Controllers\PlayerController.puml
!include .\\Controllers\QuestionController.puml
!include .\\Controllers\QuizController.puml
!include .\\Enums\Category.puml
!include .\\Enums\QuestionType.puml
!include .\\Enums\Status.puml
!include .\\Mapping\Profiles.puml
!include .\\Migrations\20220102023035_m1.puml
!include .\\Migrations\20220102023035_m1.Designer.puml
!include .\\Migrations\20220102044019_m2.puml
!include .\\Migrations\20220102044019_m2.Designer.puml
!include .\\Migrations\20220103124912_m3.puml
!include .\\Migrations\20220103124912_m3.Designer.puml
!include .\\Migrations\20220103133957_m4.puml
!include .\\Migrations\20220103133957_m4.Designer.puml
!include .\\Migrations\20220103152748_m5.puml
!include .\\Migrations\20220103152748_m5.Designer.puml
!include .\\Migrations\AppDbContextModelSnapshot.puml
!include .\\Models\Answer.puml
!include .\\Models\AnswerDTO.puml
!include .\\Models\EntityWithId.puml
!include .\\Models\EntityWithIdDTO.puml
!include .\\Models\Player.puml
!include .\\Models\PlayerDTO.puml
!include .\\Models\Question.puml
!include .\\Models\QuestionDTO.puml
!include .\\Models\Quiz.puml
!include .\\Models\QuizDTO.puml
!include .\\Objects\Rating.puml
!include .\\Objects\Unlock.puml
!include .\\Repositories\AnswerRepository.puml
!include .\\Repositories\CRUDRepository.puml
!include .\\Repositories\IAnswerRepository.puml
!include .\\Repositories\ICRUDRepository.puml
!include .\\Repositories\IPlayerRepository.puml
!include .\\Repositories\IQuestionRepository.puml
!include .\\Repositories\IQuizRepository.puml
!include .\\Repositories\PlayerRepository.puml
!include .\\Repositories\QuestionRepository.puml
!include .\\Repositories\QuizRepository.puml
!include .\\Services\AnswerService.puml
!include .\\Services\CRUDService.puml
!include .\\Services\IAnswerService.puml
!include .\\Services\ICRUDService.puml
!include .\\Services\IPlayerService.puml
!include .\\Services\IQuestionService.puml
!include .\\Services\IQuizService.puml
!include .\\Services\PlayerService.puml
!include .\\Services\QuestionService.puml
!include .\\Services\QuizService.puml
!include .\\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\obj\Debug\net5.0\QuizAppBackend.AssemblyInfo.puml
!include .\\obj\Debug\net5.0\QuizAppBackend.MvcApplicationPartsAssemblyInfo.puml
@enduml
