@startuml
interface IQuestionService {
    + GetByQuiz(idQuiz:Guid) : IEnumerable<QuestionDTO>
    + updateQuestion(questionDTO:QuestionDTO) : void
}
"ICRUDService`2" "<Question,QuestionDTO>" <|-- IQuestionService
@enduml
