@startuml
enum Category {
    Sports,
    Geography,
    Automotive,
    Music,
    Animals,
    Video_games,
    General_Culture,
    Science,
    Movies,
    Computer_science,
    Medicine,
    Literature,
}
@enduml
